### PR TITLE
Minor fixes for FIX_GameTextStyles' TDs positions & colors

### PR DESCRIPTION
**Pull request by NexiusTailer**
1. All values such as ".000000" have been truncated
2. Some values were adjusted by rounding where it's possible and reasonable, so that more stability at different resolutions can be expected
3. Some position values were corrected based on the in-game tests and gta sa data files (clock and popup boxes)
4. The colors of text and box for clock and popup boxes were also corrected after some in-game tests
5. In addition, unnecessary tabs were removed (seems like Pawno may not be so useless even today xD)

### CODE REVIEW

**Comment by Y-Less** [comment]
What resolution was this tested at?  I'm sure there are some differences at different resolutions, but the positions were basically pixel-perfect when I did them, but at maybe not the best resolution.  I'll check them at a few - should probably use positions that minimise the average error.

As for the popup colours, I just guessed those because I couldn't get a good reference with them using transparency.  Didn't think to check data files.

**Comment by Y-Less** [comment]
But thanks.

**Comment by NexiusTailer** [comment]
As for the clock, you did it really well and accurately, but there was exactly one nuance that required actually redoing everything - alignment. It should be right-aligned (= 3), since testing it in-game (by TogglePlayerClock or from singleplayer) it has always been that way. Changing the alignment unfortunately made it needed to re-adjust the positions, but now they are as accurate as they were before.

As for the resolutions related to other correction, they based on 1920x1080 with widescreen on (and re-tested on 1280x1024 with widescreen off)

> As for the popup colours, I just guessed those because I couldn't get a good reference with them using transparency. Didn't think to check data files.

Yeah, that was a challenge, but before finding out and checking the game data for some of them, I had to apply different color values (with different transparency) several times comparing screenshots from the singleplayer and mp client in the same place with the same weather/time of day to see the least color diff.

**Comment by NexiusTailer** [comment]
Do you need any additional screenshots or something to make it easier for you to review and finally merge these changes?

**Comment by Y-Less** [comment]
No, I trust you (thanks for the bump, I hadn't seen the first comment sorry).

**Comment by Y-Less** [comment]
> As for the clock, you did it really well and accurately, but there was exactly one nuance that required actually redoing everything - alignment. 

Ahh!  Well thank you.

**Pull request merged**
