### PR TITLE
Fix getting server vars.

### PR DESCRIPTION
**Pull request by Y-Less**
#73

### CODE REVIEW

**Comment by ziggi** [comment]
I think what this is should be disabled by default because this requires additional operations with the server files. Much part of the users just includes the library without reading any documentation. And they will not like the huge message in their console.

**Comment by Y-Less** [comment]
I forgot about this one.  I can modify it so it only shows the message once, and if the file doesn't exist falls back on the old code.  I can also add some filtering, so that if it does fall back on the old code, it at least checks that the parameter is a valid config option for that type, and only retrieves it if it is.

**Comment by ziggi** [comment]
It would be nice.

**Comment by Y-Less** [comment]
Done.

**Pull request merged**
