### PR TITLE
Car colours

### PR DESCRIPTION
**Pull request by Y-Less**
#36

### CODE REVIEW

**Comment by Y-Less** [comment]
I have actually tested this in-game, and it seems to work quite well, but I'd rather not push it myself until someone else has had a look.  It does actually introduce four new functions as well, but I'm not 100% on them - my general rule is if they are just exposing information already in the include then that's not too bad.  However, the `GetVehicleModelRGB` has data relating to vehicle model colours that otherwise wouldn't be required at all.

**Comment by Y-Less** [comment]
And that's why I don't just randomly push - I forgot multi-script support.

**Comment by WoutProvost** [comment]
Don't forget to update the readme, with new fuctions or fixes.

**Comment by Y-Less** [comment]
Yeah, I always forget that...

**Comment by IstuntmanI** [comment]
Amazing work you did and are still doing for the community, Y_Less. Thank you for this. I'm glad that you also installed GTA:SA-MP again and that you are somehow back in the SA-MP community. I hope that Kalcor at least watches these great community projects on GitHub, especially this fixes include, because he always said that he prefers to add new features instead of fixing scripting-fixable bugs. In my opinion a public software shouldn't have all these kinds of bugs (only beta software, but SA-MP is already a 12 years old software, it can't be considered a beta, even if it isn't at the version 1.0). I hope that he sees how hard it is to script fixes with support for everything.

I think that Kalcor should consider fixing bugs as a maximum priority, fixing all these bugs in 11.000+ lines (lots of new lines are in this pull request) with support for everything (filterscripts and defines to fix something or not) isn't too reliable. By the way, the Pawn language is really old and limited. I, for example, migrated to C++ due to this, so using this fixes include isn't possible anymore, I have to manually add things when discovering new bugs which were fixed here. I always treated bugs in my own server as a maximum priority, I can't just tell players to find workarounds to problems, like SA-MP's developer does.

This mod had a lot of potential, especially because of the great community (lots of great developers like Y_Less, Incognito, maddinat0r, kurta999, ziggi, Slice, etc.), too bad that the SA-MP team (developer and beta team) looks like it doesn't care at all about this modification.

------------

By the way, some weeks ago I decided to update [the wiki page related to bugs](http://wiki.sa-mp.com/wroot/index.php?title=Bugs&action=history) because it was ancient. Maybe some of you know additional bugs that need to be written down there. We need more attention from the developer related to all these bugs. He behaves like he is dead. He should be hired as a secret CIA agent. (exaggerating a bit, but this is somehow the truth) I think that SA-MP has enough features and the developer should concentrate a lot more on fixing these huge existing bugs (and also giving us signs that he is actually alive - maybe updates about the development status too, like what he managed to add/fix in the last weeks).

**Comment by Y-Less** [comment]
Thank you.  However, you are right - it is getting harder and harder to write these fixes in PAWN to cover all cases.  Even now I know that if you load an FS after having run some code, the fixes won't work properly - keeping all scripts loaded at different times is VERY hard (and would be much simpler in a plugin - maybe all this should be integrated in to YSF).

**Comment by rt-2** [comment]
I'd vote for this as a plugin, separated from YSF, it has a different purpose I think.

**Comment by IstuntmanI** [comment]
That is one of the reasons I decided not to use filterscripts at all. I preferred to keep everything in the gamemode and keep ```FIXES_Single``` to 1.

Same opinion as above, a separate plugin would be better. Also, using ```amx_Redirect``` to the fixed internal ones would be great, while also providing ```BAD_``` natives and nice definitions in the include. Could also allow us to dynamically enable/disable fixes and more. Each fix could have its own ID. Plugins offer huge advantages.

**Comment by Y-Less** [comment]
Making it a separate plugin would probably be the more sensible option, but also seems a little funny to me - since "YSF" literally means "Y_Less' Server Fixes".  It has not been maintained by me for a long time, but kurta999 kept the name for historical reasons.  I have actually joked about this with Slice in the past - he made SKY (**S**lice's fork of **K**urta999's version of **Y**SI), I said I should fork that again and make some stupid cyclical version.  Something like "**R**e-**I**magined **SKY**" - **RISKY**.

The API would be totally consistent with this one - so keeping `BAD_` and `FIX_` for originals and settings, of course.  If it will happen - that's another matter, as you say this include is not over 11000 lines long, and even if the plugin version was simpler I don't know how much simpler it would be.

**Comment by rt-2** [comment]
Then I think we should merge the 2 into something like CSF (Community Server Fixes).

**Comment by IstuntmanI** [comment]
Yeah, that whole **SKY** thing was pretty funny. 😆

I don't really like to use YSF because it has memory hacking for lots of addresses that will probably be outdated once a new SA-MP version comes (well, we are safe for now, 2025 is far away), even if it has pattern scanning.

But, instead, I would really like using a separate plugin just for fixes, without memory hacking like YSF. Also, the disadvantage of YSF is that it may lose its current active developer some day and not too many have the skills required to update the addresses/patterns. I know that kurta999 said that it is the core of his server (he is using sampGDK too AFAIK) so he will update YSF ASAP as long as he is around, but maybe you know that he was inactive few months due to some real life problems (at that time I thought he left SA-MP and left YSF without a developer - which was a problem due to the memory hacking). I would like to be independent, being able to update to the new version ASAP, without waiting for a plugin to be updated.

By the way, a pretty big problem I noticed since I started using sampGDK was that almost all SA-MP plugins' internal code isn't designed to be directly included - lots of internal AMX dependencies, without native C/++ functions available. I also recently suggested [better support for sampGDK for the Streamer Plugin](https://github.com/samp-incognito/samp-streamer-plugin/issues/195), I know that pretty much sampGDK gamemode developers are integrating the Streamer Plugin in their gamemode, which makes it difficult to update to newer plugin versions. I think that the sampGDK should receive a bigger support by default, by making it a sticky topic in the plugins section. People should really use it instead of Pawn. So my requirement is to make the possible future SA-MP Fixes plugin compatible for easy integration in a sampGDK gamemode. I remember that I saw other plugins that implement other development languages (PHP, JS, C#) to be using sampGDK internally too, which offers an even more important role to sampGDK.

**Comment by rt-2** [comment]
I actually need SKY for weapon-config, and it's weird it has to be included like this:
```
#include <fixes>

#include <SKY>
#include <weapon-config>//needs to be here (after SKY, before YSF, or bug)
#include <YSF>
```
Or it fails 'catastrophically' as my PC would say. It seems like I'm f*kd if the two are merged lol.

**Comment by Y-Less** [comment]
I wouldn't say merge them - just go for a new plugin.

**Comment by Y-Less** [comment]
The issue I have with writing a plugin is that I don't know how callbacks work.  For example, if I wanted to `return 0;` in `OnPlayerUpdate` to block packets, for example, can that be done from SAMPGDK?  Would it work to block them?  And could I control calling script callbacks or not?  For example, again in `OnPlayerUpdate`, if the player is fully blocked, no script callbacks are called and it just instantly returns 0.  Is that possible?  The problem with callbacks was the only reason I did it this way in the first place.

**Comment by Y-Less** [comment]
@IstuntmanI maybe you could point me in the direction of some documentation.  For this to work it would need a plugin that:

1. Could be used from both C++ gamemodes and PAWN gamemodes.  Writing something to provide wrapped functions with two APIs is easy, but I don't know enough right now about SAMPGDK to know how to redirect native calls in there to custom versions.
Does SAMPGDK just call through to the original natives, and if so, would directly hooking those (easy to do without being version-specific) mean that a separate plugin would work with both PAWN code and C++ code - essentially you would run two plugins that would have no knowledge of each other, but because of the consistent API, just work.  Or is this what current plugins do and you want a more direct interface (which makes sense, but what would that be)?

2. Can interrupt callbacks.  Again, from both PAWN and C++.  Right now, the only way I know to do this is:
```pawn
public OnPlayerUpdate(playerid)
{
    if (FixesPlugin_OnPlayerUpdate(playerid) == -1) return 0;
    return NextALS_OnPlayerUpdate(playerid);
}
```
That would still require a PAWN script to be running, and I doubt it would work with C++ modes at all.

3. Once a basic structure is set up, porting the code over should not be too hard (and will result in much nicer code - no more single monolithic file (for which there are reasons)).  But it is getting a structure that support the features going that is the hard part.  Do you have any interest in assisting with that first stage, since you surely know far more about plugin development now than I do (obviously I can write C++ and plugins, but have not done anything like this for many years, so the state of the art has advanced a long way)?  As I say, once the structure is working, porting fixes would not require help if you weren't interested (though it would be useful).

**Comment by IstuntmanI** [comment]
Doing a custom ```return``` in a callback is handled by the sampGDK, it won't be called in gamemode and filterscripts if ```return 0``` (just like the regular returns),  but it is still called in other plugins (tested this with the streamer plugin, the original ```OnPlayerPickUpPickup``` [for example] is still called in my gamemode plugin, but not in the Pawn gamemode/filterscripts). You can see an example for ```OnPlayerCommandText``` here: https://github.com/Zeex/sampgdk/blob/master/README.md .

1. I noticed this in the TimerFix plugin: it uses the ```amx_Redirect``` function for the fixed ```GetTickCount```, ```KillTimer``` and ```SetTimer(Ex)``` functions: 
https://github.com/udan11/samp-plugin-timerfix/blob/master/src/main.cpp#L77-L80
I didn't found that function in the original sampsdk, but I found it in a modified "```amxplugin2.cpp```" file from the sampsdk (probably added by Dan, as maddinat0r's sampsdk is a fork of Dan's, which already has ```amx_redirect``` included since the initial commit): 
https://github.com/udan11/samp-plugin-sdk/blob/a425b5b3d9f3dc1fe1a3306ee92996ec103d7e28/amxplugin2.cpp#L38
I don't know if the correct ```amx_Redirect``` redirected function will be used by ```sampgdk::<Function>``` in other plugins or if the sampGDK will use the SA-MP native unhooked functions. I think it just calls the SA-MP native ones, as I think we are able to use ```amx_Redirect``` on a custom amx function that is using a default ```sampgdk::<Function>``` function. This is probably why we should be able to include the custom plugin in our gamemodes, while providing ```namespace Fixes```, so instead of ```sampgdk::<Function>``` we would call ```Fixes::<Function>``` (the "more direct interface" thing). Having a C++ gamemode is pretty limited, I noticed all kind of problems of the compatibility with other plugins. The problem in this would be to provide compatibility for direct C++ calls while also registering the natives to be called in Pawn gamemode/filterscripts.
2. Well, the plugins are called first on a callback call, then the filterscripts and then the gamemode. This is how you would do it, if I understood correctly your question:
```C++
PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerUpdate(int playerid)
{
	if( PlayerCrashesOthers( playerid ) )
		return false; // won't call in gamemode/filterscripts and the update will be cancelled >
// but AFAIK it is still called in other plugins, not sure what happens if those return true. I guess that it still won't be called in gamemode/filterscripts

	return true; // will automatically call OnPlayerUpdate from other plugins, then filterscripts and then from the gamemode
}
```
Also, additionally, if you want to create a custom callback you need to execute it in all the amx instances addresses (you need to save the amx pointer in the ```AmxLoad``` callback in the plugin). I took most of this from the Streamer and TimerFix Plugins:
```C++
const AMX_NATIVE_INFO NATIVES[] =
{
    {"KickAss", Natives::KickAss},
};
std::set<AMX*> amxinterfaces;
PLUGIN_EXPORT int PLUGIN_CALL AmxLoad(AMX *amx)
{
    amxinterfaces.insert(amx);
    return amx_Register(amx, NATIVES, -1);
}
```
(I guess you already knew that part)
```C++
PLUGIN_EXPORT bool PLUGIN_CALL OnPlayerUpdate(int playerid)
{
	for (std::set<AMX*>::iterator i = amxinterfaces.begin(); i != amxinterfaces.end(); ++i)
	{
		int amxIndex = 0;
		cell retval = 0;
		if (!amx_FindPublic(*i, "OnPlayerThing", &amxIndex)) // it won't proceed if that amx interface doesn't have it
		{
			amx_Push(*i, playerid);
			amx_Exec(*i, &retval, amxIndex);

			if(retval == 0) // that callback from that amx interface returned 0, let's also return 0 !
				return false;
		}
	}

	return true;
}
```
Not sure about this too, but I noticed that I had some problems with custom callbacks when multiple filterscripts were loaded. I think that ```amx_Exec``` was executing the callback multiple times, not only once. ```sampGDK``` provides a ```OnPublicCall``` to be used if there's such a custom callback called from another plugin. It may be buggy with multiple AMX interfaces (one gamemode [there is always at least one AMX interface, of course] and at least one filterscript), not sure. When it was buggy like that I also had lots of memory corruption because of all the AMX manipulation from the MySQL Plugin (especially the damn log-core !), so that's why I'm not sure if it is actually a problem from the sampGDK.

3. Well, I would really like to help with that, but what stopped me to add things in the fixes include were all the style rules and also the micro-optimizations and lot of bit-wise code that you want in it. I thought that I would make mistakes related to the styling and 100% related to optimization (you are too extreme about that !). As I suggested in that streamer plugin issue for the sampGDK support, there should be some ```FIXES_REMOVE_AMX``` definition. If it is defined the plugin should be able to be directly copy-pasted in a sampGDK plugin without registering the natives. It should also provide functions as "hooks" (well, these aren't hooks, but they are pretty close), so instead of
```PLUGIN_EXPORT int PLUGIN_CALL AmxLoad(AMX *amx) { ... }```
that line should be changed into
```C++
namespace Fixes { namespace Internal {
....
int AmxLoad(AMX *amx) { ... }
....
}
```

if the ```FIXES_REMOVE_AMX``` definition is present, and we should add that function call under our main ```AmxLoad```.
In that Streamer Plugin issue I also suggested for the AMX functions to be still registered if directly including the plugin in our C++ gamemode, but I think that it would be too hard (not as hard as the current samp-fixes definitions !), as we have to store in the AMX in a different way and also need to do some casting.

I hope that I helped you, at least a bit, with my response. If you don't want to provide a plugin for all these fixes I completely understand you, it is a bit messy because of the AMX.

Personally, I really hate to work with the AMX, this is why I didn't register any AMX function from my gamemode (even though they would help with test-filterscripts !). Providing functions with the AMX native support is shitty. This is also why I would like to include everything in the C++ gamemode, without the ability to keep any AMX native function. (also, it would gain more speed, as AMX handling is additional processing)

**Comment by Y-Less** [comment]
Do bear in mind that a fix that doesn't exactly meet guidelines and is not as perfectly optimised as it could be, is still better than no fix at all!  There are rarely cleanups that MUST be made, I'm sure not all the code is perfectly consistent even now.  We'd much rather have something written, however it is written, than nothing at all.

**Comment by Y-Less** [comment]
I propose the name "NYSFBCSFMCBYAZ":

Not Y_Less' Server Fixes, But Community Server Fixes Mostly Curated By Y_Less And Ziggi

Edit:  I did once release a library called QWERTYUIOP (and made an AZERTYUIOP variant for inclusion):

Quaint Wrappers Enabling Relatively Terse YSI Usage Instead Of Perplexity.

I'll try come up with a name for ASDFGHJKL.

**Comment by SysadminJeroen** [comment]
That is a catchy name.

**Comment by Y-Less** [comment]
Assorted Server Doable Fixes, Generally Helping Johns Keep Laughing
All Server Doable Fixes, Getting Hackers Just Killing Logic
Amazing Selected Dainty Fixes, Gestating Highly Juicy Kumquat Luxuriance

**Comment by IstuntmanI** [comment]
Oh god, not this thing again. When I read your "NYSFBCSFMCBYAZ" suggestion I immediately thought about that old "AZERTYUIOP" thing.
That "Gestating" tho' .

Well, for all the raging bastards like me, I would suggest the name "FFEE **FAC**BEIB": "Fixes For Every Existing Function And Callback Because Everything Is Bugged". They could simply call it "FACBEIB". Slogan: Your server is bugged ? FACBEIB !
Tried to find something for "KALCORPLZ" but I just can't.

**Comment by SysadminJeroen** [comment]
**S**erver **H**elper **I**ntergrated **P**lugin **F**ix **U**nmaintained **C**ode **K**alcor.

A.k.a. SHIPFUCK

**Comment by IstuntmanI** [comment]
Well, you are just shipping fucks actually. SHIPFUCK

Well, seriously speaking, the plugin would need a valid name. "Community Fixes Plugin" maybe.

**Comment by SysadminJeroen** [comment]
If someone actually makes the plugin and names it after a curseword or slur I'll put it in my signature until it is no longer maintained.

**Comment by Y-Less** [comment]
Upgraded
Scripting
Experience,
Fixing
Unexpected
Logic

- USEFUL!

**Comment by Y-Less** [comment]
I'd also like to point out, this is actually a pull request with code for integration...

**Comment by Y-Less** [comment]
@IstuntmanI just pointed out a serious flaw in the implementation.  I have an idea of how to fix it though (and actually I think the new method uses less memory as a side-effect).

**Comment by IstuntmanI** [comment]
Also, I see this in ```carcols.dat``` for example:
```infernus, 12,1, 64,1, 123,1, 116,1, 112,1, 106,1, 80,1, 75,1```
what it means ? That the only ```color2``` valid is 1, while there are only those few ```color1``` values ? AFAIK, Infernus and a lot of other vehicles support lots of colors as the primary one, even the ones from 128 to 255.

Also, I don't think you have from where to gain those RRGGBB values for the colors above 128. For my server I'm using a function to retrieve the hex codes of vehicle colors, I can't remember where I found this array, you may want to use this one, I didn't find any mistake ingame:
```cpp
new VehicleColorsHex[ 256 ] =
{
	// The existing colours from San Andreas
	0x000000FF, 0xF5F5F5FF, 0x2A77A1FF, 0x840410FF, 0x263739FF, 0x86446EFF, 0xD78E10FF, 0x4C75B7FF, 0xBDBEC6FF, 0x5E7072FF,
	0x46597AFF, 0x656A79FF, 0x5D7E8DFF, 0x58595AFF, 0xD6DAD6FF, 0x9CA1A3FF, 0x335F3FFF, 0x730E1AFF, 0x7B0A2AFF, 0x9F9D94FF,
	0x3B4E78FF, 0x732E3EFF, 0x691E3BFF, 0x96918CFF, 0x515459FF, 0x3F3E45FF, 0xA5A9A7FF, 0x635C5AFF, 0x3D4A68FF, 0x979592FF,
	0x421F21FF, 0x5F272BFF, 0x8494ABFF, 0x767B7CFF, 0x646464FF, 0x5A5752FF, 0x252527FF, 0x2D3A35FF, 0x93A396FF, 0x6D7A88FF,
	0x221918FF, 0x6F675FFF, 0x7C1C2AFF, 0x5F0A15FF, 0x193826FF, 0x5D1B20FF, 0x9D9872FF, 0x7A7560FF, 0x989586FF, 0xADB0B0FF,
	0x848988FF, 0x304F45FF, 0x4D6268FF, 0x162248FF, 0x272F4BFF, 0x7D6256FF, 0x9EA4ABFF, 0x9C8D71FF, 0x6D1822FF, 0x4E6881FF,
	0x9C9C98FF, 0x917347FF, 0x661C26FF, 0x949D9FFF, 0xA4A7A5FF, 0x8E8C46FF, 0x341A1EFF, 0x6A7A8CFF, 0xAAAD8EFF, 0xAB988FFF,
	0x851F2EFF, 0x6F8297FF, 0x585853FF, 0x9AA790FF, 0x601A23FF, 0x20202CFF, 0xA4A096FF, 0xAA9D84FF, 0x78222BFF, 0x0E316DFF,
	0x722A3FFF, 0x7B715EFF, 0x741D28FF, 0x1E2E32FF, 0x4D322FFF, 0x7C1B44FF, 0x2E5B20FF, 0x395A83FF, 0x6D2837FF, 0xA7A28FFF,
	0xAFB1B1FF, 0x364155FF, 0x6D6C6EFF, 0x0F6A89FF, 0x204B6BFF, 0x2B3E57FF, 0x9B9F9DFF, 0x6C8495FF, 0x4D8495FF, 0xAE9B7FFF,
	0x406C8FFF, 0x1F253BFF, 0xAB9276FF, 0x134573FF, 0x96816CFF, 0x64686AFF, 0x105082FF, 0xA19983FF, 0x385694FF, 0x525661FF,
	0x7F6956FF, 0x8C929AFF, 0x596E87FF, 0x473532FF, 0x44624FFF, 0x730A27FF, 0x223457FF, 0x640D1BFF, 0xA3ADC6FF, 0x695853FF,
	0x9B8B80FF, 0x620B1CFF, 0x5B5D5EFF, 0x624428FF, 0x731827FF, 0x1B376DFF, 0xEC6AAEFF, 0x000000FF,

	// SA-MP extended colours (0.3x)
	0x177517FF, 0x210606FF, 0x125478FF, 0x452A0DFF, 0x571E1EFF, 0x010701FF, 0x25225AFF, 0x2C89AAFF, 0x8A4DBDFF, 0x35963AFF,
	0xB7B7B7FF, 0x464C8DFF, 0x84888CFF, 0x817867FF, 0x817A26FF, 0x6A506FFF, 0x583E6FFF, 0x8CB972FF, 0x824F78FF, 0x6D276AFF,
	0x1E1D13FF, 0x1E1306FF, 0x1F2518FF, 0x2C4531FF, 0x1E4C99FF, 0x2E5F43FF, 0x1E9948FF, 0x1E9999FF, 0x999976FF, 0x7C8499FF,
	0x992E1EFF, 0x2C1E08FF, 0x142407FF, 0x993E4DFF, 0x1E4C99FF, 0x198181FF, 0x1A292AFF, 0x16616FFF, 0x1B6687FF, 0x6C3F99FF,
	0x481A0EFF, 0x7A7399FF, 0x746D99FF, 0x53387EFF, 0x222407FF, 0x3E190CFF, 0x46210EFF, 0x991E1EFF, 0x8D4C8DFF, 0x805B80FF,
	0x7B3E7EFF, 0x3C1737FF, 0x733517FF, 0x781818FF, 0x83341AFF, 0x8E2F1CFF, 0x7E3E53FF, 0x7C6D7CFF, 0x020C02FF, 0x072407FF,
	0x163012FF, 0x16301BFF, 0x642B4FFF, 0x368452FF, 0x999590FF, 0x818D96FF, 0x99991EFF, 0x7F994CFF, 0x839292FF, 0x788222FF,
	0x2B3C99FF, 0x3A3A0BFF, 0x8A794EFF, 0x0E1F49FF, 0x15371CFF, 0x15273AFF, 0x375775FF, 0x060820FF, 0x071326FF, 0x20394BFF,
	0x2C5089FF, 0x15426CFF, 0x103250FF, 0x241663FF, 0x692015FF, 0x8C8D94FF, 0x516013FF, 0x090F02FF, 0x8C573AFF, 0x52888EFF,
	0x995C52FF, 0x99581EFF, 0x993A63FF, 0x998F4EFF, 0x99311EFF, 0x0D1842FF, 0x521E1EFF, 0x42420DFF, 0x4C991EFF, 0x082A1DFF,
	0x96821DFF, 0x197F19FF, 0x3B141FFF, 0x745217FF, 0x893F8DFF, 0x7E1A6CFF, 0x0B370BFF, 0x27450DFF, 0x071F24FF, 0x784573FF,
	0x8A653AFF, 0x732617FF, 0x319490FF, 0x56941DFF, 0x59163DFF, 0x1B8A2FFF, 0x38160BFF, 0x041804FF, 0x355D8EFF, 0x2E3F5BFF,
	0x561A28FF, 0x4E0E27FF, 0x706C67FF, 0x3B3E42FF, 0x2E2D33FF, 0x7B7E7DFF, 0x4A4442FF, 0x28344EFF
};
```

Also (also, I may use the word also too much *ba dum tss*), is there any need to pack the sh*t out of them ? Your whole nazi-optimization makes the processor to think harder (I think) when there's no need. The machines today have lots of RAM and those are pretty small. I don't think there's any need to do all that hard coding. I think that the server FPS is more important than the RAM usage.

**Comment by Y-Less** [comment]
No there is no need for packing, but when I thought I only needed one byte, and PAWN supports that natively, there's no point not doing it.  Also, you probably got that array from the very link you gave me :)

Yes, all cars support all colours, but some colours and combinations may look terrible or not suit the type of vehicle - sports cards tend to be bright flashy colours, police cars are black and white, family cars are pastels, etc.  The colours in carcols.dat are not all the colours that a vehicle supports, but all the colours they are defined to have by default - that's why you won't see a pink and green ambulance in the game, because they haven't been given that combination; but you can manually make one.

**Comment by Y-Less** [comment]
Also, I always try to optimise for CPU, not memory, because as you say computers have lots of RAM.  I have said exactly that for many years, but packed arrays are a free trick - just do `array{0}` instead of `array[0]`....

**Comment by IstuntmanI** [comment]
Aw, yeah, I didn't scroll this time that further in the page to notice the array, I was just looking at the photos. 😆 I think that's where I got the array from, indeed.

Aw, you are right about the colors. I prefer to offer all available color combinations for my server, even really bright colors to family cars. I have to remember that you are trying to fix the ```-1``` behavior, to make it like how SA-MP wants it to behave like, but with sync in addition. In my server I just use ```random( 256 )``` because I want all the possible colors.

Well, I didn't want to say about that little ```{x}``` instead of ```[x]``` trick, that's pretty easy and useful, but more about things like these:
- ```if (FIXES_gscVehicleMods[(modelid - 400) * 6 + (componentid - 1000 >>> 5)] & 1 << (componentid - 1000 & 0b00011111))```

(this is some pretty ridiculous optimization, I kinda like it actually, it's a pretty genius way) I know that this is possibly the only way to store valid components without creating a ridiculous number of arrays/few huge arrays.

- ```static stock FIXES_gsSpace[] = " ";```
- ```static stock FIXES_gscKick[] = "_FIXES_Kick"```

I don't think that simply using ```" "``` where needed hurts anyone, there's no need for such extra optimizations. Also, ```"_FIXES_Kick"``` should be used to call the function with the timer, the function can't change its name automatically/with that definition anyway.

Using a little more RAM and making the code easier to modify is the best practice in my opinion, for a community project or even for a private project that has frequent updates. There's no need to brain storm few things or write too much just for the sake of saving few nanoseconds and bytes from the compiled file/RAM. I like optimizing things out too, but not in such a manner. That's only my opinion, but you are a lot better than me at coding (and that's for sure - you managed to use those ```#emit``` codes to give us the amazing ```YSI``` library [it uses lots of Pcode, that's how it is called AFAIK], I find that pretty much impossible) and maybe I'm missing something or I'm pretty wrong, I just prefer to make changes easier, without the need to create a variable for any string used anywhere (faster development, no need to respect some additional style rules for that variable too or to find the place where to put it).

**Pull request closed without merging**
